export const UPDATE_PROJECT_STARS = 'UPDATE_PROJECT_STARS';
export const UNJOIN_TO_PROJECT_CONTRIBUTORS_START = 'UNJOIN_PROJECT_START';
export const UNJOIN_TO_PROJECT_CONTRIBUTORS_END = 'UNJOIN_TO_PROJECT_CONTRIBUTORS_END';
export const JOIN_TO_PROJECT_CONTRIBUTORS_START = 'JOIN_TO_PROJECT_CONTRIBUTORS_START';
export const JOIN_TO_PROJECT_CONTRIBUTORS_END = 'JOIN_TO_PROJECT_CONTRIBUTORS_END';
