export const STAR_PROJECT_START = 'STAR_PROJECT_START';
export const STAR_PROJECT_END = 'STAR_PROJECT_END';
export const UNSTAR_PROJECT_START = 'UNSTAR_PROJECT_START';
export const UNSTAR_PROJECT_END = 'UNSTAR_PROJECT_END';
export const UPDATE_PROJECT_STARS = 'UPDATE_PROJECT_STARS';
