export const LOAD_STARRED_PROJECTS_START = 'LOAD_STARRED_PROJECTS_START';
export const LOAD_STARRED_PROJECTS_END = 'LOAD_STARRED_PROJECTS_END';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_END = 'LOGIN_END';
export const LOGOUT = 'LOGOUT';