export const ADD_STARRED_PROJECT = 'ADD_STARRED_PROJECT';
export const REMOVE_STARRED_PROJECT = 'REMOVE_STARRED_PROJECT';
export const LOAD_STARRED_PROJECTS_START = 'LOAD_STARRED_PROJECTS_START';
export const LOAD_STARRED_PROJECTS_END = 'LOAD_STARRED_PROJECTS_END';