export const ADD_MESSAGE = 'ADD_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const LOADING_PROCESS_START = 'LOADING_PROCESS_START';
export const LOADING_PROCESS_END = 'LOADING_PROCESS_END';
