export const GET_PARTNER_TEAMS_LIST_START = 'GET_PARTNER_TEAMS_LIST_START';
export const GET_PARTNER_TEAMS_LIST_END = 'GET_PARTNER_TEAMS_LIST_END';
export const DELETE_TEAM_START = 'DELETE_TEAM_START';
export const DELETE_TEAM_END = 'DELETE_TEAM_END';
export const SAVE_TEAM_START = 'SAVE_TEAM_START';
export const SAVE_TEAM_END = 'SAVE_TEAM_END';
export const GET_PARTNER_TEAM_START = 'GET_PARTNER_TEAM_START';
export const GET_PARTNER_TEAM_END = 'GET_PARTNER_TEAM_END';