saveResults:
  name: ${self:provider.stage}-saveResults
  role: saveResultsRole
  handler: handlers/survey/saveResults/handler.handler
  timeout: 10
  events:
  - http:
      path: /survey/results/save
      method: post
      cors: true
      authorizer:
        name: authorizer
        resultTtlInSeconds: 300
        identitySource: method.request.header.Authorization
        identityValidationExpression: .*
        type: token
