getLikedProjectsRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: ${self:provider.stage}-getLikedProjectsRole
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
          Action:
            - sts:AssumeRole
            - ec2:CreateNetworkInterface,
            - ec2:DescribeNetworkInterfaces,
            - ec2:DeleteNetworkInterface
